### ISSUE TITLE
No configuration provided for App.scss

### ISSUE THREAD

**Issue by 0924698** [vikpe/react-webpack-typescript-starter#12]
Hi, I'm getting this error when I try to run this project.

> react-webpack-typescript-starter@0.1.0 start-dev /Users/Me/Projects/klerenzooi/client
> webpack-dev-server --config=configs/webpack/dev.js

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
✖ ｢wdm｣: Error: No configuration provided for /Users/Me/Projects/klerenzooi/client/src/assets/scss/App.scss
    at module.exports (/Users/Me/Projects/klerenzooi/client/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at searchForConfig.then.then.config (/Users/Me/Projects/klerenzooi/client/node_modules/stylelint/lib/getConfigForFile.js:49:15)

Do you know how I can fix this?

**Comment by vikpe** [comment]
Hi.

I did a fresh install and I don't get this error.

It seems like stylelint is unable to find a config. The config is found in `.stylelintrc` which simply extends the standard config.

```json
{
  "extends": "stylelint-config-standard"
}
```

**Comment by vikpe** [comment]
You can test to remove the StyleLintPlugin ([line 46 in configs/webpack/common.js](https://github.com/vikpe/react-webpack-typescript-starter/blob/master/configs/webpack/common.js#L46)).

```
plugins: [
  new CheckerPlugin(),
  new StyleLintPlugin(), <-- THIS
  new HtmlWebpackPlugin({template: 'index.html.ejs',}),
],
```
