### ISSUE TITLE
"Error: No configuration provided" error on clone/install/start

### ISSUE THREAD

**Issue by samuelneff** [vikpe/react-webpack-typescript-starter#13]
I cloned the repo, ran npm install, and then ran npm start. I get this error. When I try to load the page in a browser it says no data was sent.

```
$ npm start

> ppp@0.0.1 start C:\ppp\ppp-ui
> npm run start-dev


> ppp@0.0.1 start-dev C:\ppp\ppp-ui
> webpack-dev-server --config=configs/webpack/dev.js

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
× ｢wdm｣: Error: No configuration provided for C:\ppp\ppp-ui\src\assets\scss\App.scss
    at module.exports (C:\ppp\ppp-ui\node_modules\stylelint\lib\utils\configurationError.js:8:28)
    at searchForConfig.then.then.config (C:\ppp\ppp-ui\node_modules\stylelint\lib\getConfigForFile.js:49:15)
    at <anonymous>
i ｢wdm｣: wait until bundle finished: /
```

Thanks.

**Comment by vikpe** [comment]
@samuelneff for some reason (I can't reproduce the error), the config for stylelint isn't found.

You can disable stylelint ([as described here](https://github.com/vikpe/react-webpack-typescript-starter/issues/12)) or re-pull this repo as I've decided to remove stylelint.

**Comment by samuelneff** [comment]
Thank you. That resolved it.
