### ISSUE TITLE
mozjpeg not compiling when installing

### ISSUE THREAD

**Issue by paveltrufi** [vikpe/react-webpack-typescript-starter#5]
I am currently having some problems to install one of the dependencies. The thrown error is below:
```
> mozjpeg@4.1.1 postinstall /home/pavel/Intellij Projects/react-webpack-typescript-starter/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/home/pavel/Intellij Projects/react-webpack-typescript-starter/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/home/pavel/Intellij Projects/react-webpack-typescript-starter/node_modules/mozjpeg/vendor" --bindir="/home/pavel/Intellij Projects/react-webpack-typescript-starter/node_modules/mozjpeg/vendor" --libdir="/home/pavel/Intellij Projects/react-webpack-typescript-starter/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:22: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by vikpe** [comment]
@paveltrufi Are you using Mac? I did a search and found [the same problem being discussed](https://github.com/JeffreyWay/laravel-mix/issues/1271) and solved in other repos.

**Comment by paveltrufi** [comment]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

**Comment by vikpe** [comment]
If you do a plain install of imagemin-mozjpeg, does it work?
```bash
echo {} > package.json
npm install --save imagemin-mozjpeg
```

**Comment by paveltrufi** [comment]
Actually not. It seems like the problem is with the package itself. Anyway, why do I need this dependency for? I've been using your project structure and it didn't gave me any error :smiley:

**Comment by vikpe** [comment]
@paveltrufi `imagemin-mozjpeg` is part of `webpack-image-loader` which loads jpeg images.

Try importing a jpeg image in your source file, eg:
```javascript
import 'example.jpg' from '../assets/example.jpg';
```
